# This file tells Netlify how to build your site.
# It's the most reliable way to set the functions directory.
[build]

# This tells Netlify that your serverless functions are in a folder named "functions".
functions = "functions"

